[log]
; DEBUG | INFO | WARN | ERROR
logLevel = INFO

[mtls / common]
; set either of these
; mtlsCaCertPath takes precedence if both present
mtlsCaCertPath =
mtlsCaCertURL =

[mtls / client]
mtlsClientCertPath =
mtlsClientPrivateKeyPath =

[mtls / server]
mtlsServerCertPath =
mtlsServerPrivateKeyPath =
mtlsCrlURL = http://c2r.mygaru.com/crl/myGaru-A1.crl
mtlsCrlCheckInterval = 1h
mtlsServerListenAddr =

[forwarding]
authMWForwardTrafficAddr = https://en.wikipedia.org
authMWForwardTimeout = 10s