name: Deploy Image to storage server box.mygaru.com

on:
  workflow_dispatch:
    inputs:
      service:
        description: "trigger build/deploy"
        required: true
        type: choice
        default: "start"
        options:
          - start

jobs:
  build:
    runs-on: [self-hosted, mygaru] 
    environment: azconn
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      
      - name: Build and export Docker image as tar
        uses: docker/build-push-action@v5 
        with:
          context: .
          file: ./Dockerfile 
          tags: ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.run_number }} 
          outputs: type=docker,dest=/tmp/${{ github.event.repository.name }}-${{ github.run_number }}.tar
        
      - name: show image
        run: | 
            echo "IMAGE TAG: ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.run_number }}"
            echo "IMAGE FILE NAME: ${{ github.event.repository.name }}-${{ github.run_number }}.tar"
    
      - name: Upload image to storage
        uses: appleboy/scp-action@v1
        with:
          host: u458881.your-storagebox.de
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.STORAGE_SSH_KEY }}
          source: ./tmp/${{ github.event.repository.name }}-${{ github.run_number }}.tar
          target: /home/filestorage/
