name: Deploy ID-check 

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'
jobs:
  build:
    runs-on: [self-hosted, mygaru] 
    environment: k8s
    env:
      PROJECT_NAME: cloud
      VAULT_TOKEN_EXPIRATION: 0h
      VAULT_SECRET_ID_TTL: 8760h
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Install Vault CLI
        run: |
          VAULT_VERSION="1.14.1"
          curl -sLo vault.zip "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip"
          unzip vault.zip
          sudo mv vault /usr/local/bin/vault
          vault --version

      - name: Vault Post-Installation Configuration
        id: vault_post_install
        run: |
          # Установка переменных окружения в зависимости от типа окружения (dev/prod)
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
          export VAULT_HOST=${{ secrets.VAULT_HOST }}

          # Проверяем, включена ли уже аутентификация AppRole
          if ! vault auth list -address="https://$VAULT_HOST" | grep -q '^approle/'; then
            vault auth enable -address="https://$VAULT_HOST" approle
          else
            echo "AppRole auth method is already enabled."
          fi

          if vault kv get -address="https://$VAULT_HOST" secrets/${{ env.PROJECT_NAME }}/prod/${{ github.event.repository.name }} > /dev/null 2>&1; then
            vault kv patch -address="https://$VAULT_HOST" secrets/${{ env.PROJECT_NAME }}/prod/${{ github.event.repository.name }} REVISION="${{ github.ref_name }}"
          else
            vault kv put -address="https://$VAULT_HOST" secrets/${{ env.PROJECT_NAME }}/prod/${{ github.event.repository.name }} REVISION="${{ github.ref_name }}"
          fi
          
          vault policy write -address="https://$VAULT_HOST" ${{ github.event.repository.name }}-prod-policy -<<EOF
          path "secrets/data/${{ env.PROJECT_NAME }}/prod/${{ github.event.repository.name }}" {
            capabilities = [ "read" ]
          }
          EOF
          
          vault write -address="https://$VAULT_HOST" auth/approle/role/${{ github.event.repository.name }}-prod-role \
              secret_id_ttl="${{ env.VAULT_SECRET_ID_TTL }}" \
              token_policies="${{ github.event.repository.name }}-prod-policy" \
              token_ttl="${{ env.VAULT_TOKEN_EXPIRATION }}" \
              token_max_ttl="${{ env.VAULT_TOKEN_EXPIRATION }}" \
              token_type="service"

          role_id=$(vault read -address="https://$VAULT_HOST" auth/approle/role/${{ github.event.repository.name }}-prod-role/role-id -format=json | jq -r '.data.role_id')
          echo "ROLE_ID=$role_id" >> $GITHUB_ENV

      - name: Retrieve secret_id from Vault
        id: vault_secret_id
        run: |
          # Установка переменных окружения в зависимости от типа окружения (dev/prod)
          export VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}
          export VAULT_HOST=${{ secrets.VAULT_HOST }}

          secret_id=$(vault write -address="https://$VAULT_HOST" -f auth/approle/role/${{ github.event.repository.name }}-prod-role/secret-id -format=json | jq -r '.data.secret_id')
          echo "SECRET_ID=$secret_id" >> $GITHUB_ENV
          echo "Secret_ID from Vault: $secret_id"

      - name: Formulate SECRET_URI
        id: formulate_secret_uri
        run: |
          VAULT_HOST=${{ secrets.VAULT_HOST }}
          SECRET_URI="vault://${{ env.ROLE_ID }}:${{ env.SECRET_ID }}@$VAULT_HOST/secrets/data/${{ env.PROJECT_NAME }}/prod/${{ github.event.repository.name }}?&tokenExpiration=${{ env.VAULT_TOKEN_EXPIRATION }}"
          echo "SECRET_URI=$SECRET_URI" >> $GITHUB_ENV
          echo "SECRET_URI: $SECRET_URI"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DEPLOY_GHCR_USERNAME }}
          password: ${{ secrets.DEPLOY_GHCR_PASSWORD }}

      - name: Get DATE Env
        shell: bash
        run: echo "DATE=$(date '+%Y-%m-%dT%H:%M:%S%z' | sed 's@^.\{22\}@&:@')" >> $GITHUB_ENV
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          pull: true
          build-args: |
            VAULT_URI=${{ env.SECRET_URI }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}

  deploy:
    needs: build
    runs-on: [self-hosted, mygaru]
    environment: k8s
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up Kubernetes Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Replace TAG_NAME in ArgoCD application file
        run: |
          ARGO_APP_FILE="./cfg/argo-application.yml"
          sed -i 's/TAG_NAME/${{ github.ref_name }}/g' "$ARGO_APP_FILE"

      - name: Deploy using kubectl
        run: |
          kubectl apply -f "./cfg/argo-application.yml"
      - name: Healthcheck
        run: |
          APP_NAME="mygaru-dcr-id-check"
          NAMESPACE="argocd"
          MAX_ATTEMPTS=3
          WAIT_TIME=20

          for attempt in $(seq 1 $MAX_ATTEMPTS); do
            echo "$attempt: Checking state for $APP_NAME..."
            STATUS=$(kubectl get application "$APP_NAME" -n "$NAMESPACE" -o jsonpath='{.status.sync.status} {.status.health.status}')
            echo "Status: $STATUS"

            if [[ "$STATUS" == "Synced Healthy" ]]; then
              echo "Nice!"
              exit 0
            else
              echo "Not healthy."
              if [ "$attempt" -lt "$MAX_ATTEMPTS" ]; then
                sleep "$WAIT_TIME"
              fi
            fi
          done

          echo "Not healthy after $MAX_ATTEMPTS retries."
          exit 1
